provider: local
major-version: 0
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
env:
  LOCAL_TOKEN: ${{ secrets.LOCAL_TOKEN }}
plugins:
  - name: aws
    version: "6.14.0"
publish:
  sdk: "all,!python"
