# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .file import *
from .get_file import *
from .get_sensitive_file import *
from .provider import *
from .sensitive_file import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "local",
  "mod": "index/file",
  "fqn": "pulumi_local",
  "classes": {
   "local:index/file:File": "File"
  }
 },
 {
  "pkg": "local",
  "mod": "index/sensitiveFile",
  "fqn": "pulumi_local",
  "classes": {
   "local:index/sensitiveFile:SensitiveFile": "SensitiveFile"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "local",
  "token": "pulumi:providers:local",
  "fqn": "pulumi_local",
  "class": "Provider"
 }
]
"""
)
